versions module
plugoinc/ocpi-openapi pull request #13
Opened 2023-08-31 08:57 UTC by ThaddeusJiang

- feat: 🎸 versions module
- chore: 🤖 version 0.0.8

2023-08-31 11:27 UTC, Ko1103 commented on openapi/paths/{version}_details.yaml
> +    - Configurations
Versionsでいいと思います。ConfigurationにしちゃうとCredentialsもここに入ってくるので

2023-08-31 11:33 UTC, Ko1103 commented on openapi/paths/{version}_details.yaml
`openapi/paths/{version}.yaml`で十分な気がするのですが

2023-08-31 11:34 UTC, Ko1103 commented on openapi/paths/versions.yaml
> +    - Configurations
Versions tagでいいとおもいます。

2023-08-31 11:35 UTC, Ko1103 commented on openapi/components/schemas/InterfaceRoleEnum.yaml
filename InterfaceRole.yaml is enough to describe this.

2023-08-31 11:36 UTC, Ko1103 commented on openapi/components/schemas/ModuleIDEnum.yaml
Same as InterfaceRole, ModuleId.yaml will be enough

2023-08-31 11:36 UTC, Ko1103 commented on openapi/components/schemas/VersionNumberEnum.yaml
VersionNumber.yaml

2023-08-31 11:37 UTC, Ko1103 requested changes
Please read comments and fix.

2023-09-04 00:43 UTC, ThaddeusJiang commented on openapi/paths/versions.yaml
> +    - Configurations
@Ko1103 `Configurations` にした理由は OCPI の Type を流用したいです。

![CleanShot 2023-09-04 at 09 42 55](https://github.com/plugoinc/ocpi-openapi/assets/17308201/09febbf5-44a5-4f97-8579-b9d8d966eac6)

2023-09-04 01:38 UTC, Ko1103 commented on openapi/paths/versions.yaml
> +    - Configurations
Configurations Module is Typeですね、its not a real module.
tagはresourceを分類するために(like Locations, CDRs)に作るべきで、Versionsがいいです。

If これをConfigurations Moduleにする -> Locations CRSs, TokensはFunctional Moduleなのでtagも Functional Moduleになる -> It's kind of odd, isn't it?

2023-09-04 04:35 UTC, Ko1103 approved these changes
LGTM!

2023-09-04 04:35 UTC, merged