OCPI get /tariffs
plugoinc/ocpi-openapi pull request #17
Opened 2023-10-23 03:04 UTC by ThaddeusJiang

2023-10-23 23:53 UTC, Ko1103 commented on openapi/components/schemas/TariffRestrictions.yaml
> +      Start time of day in local time, the time zone is defined in the time_zone field of the Location, for example 13:30, valid from this time of the day. Must be in 24h format with leading zeros. H
patternを設定できますか？regexを入れれば良いと思います。
https://swagger.io/docs/specification/data-models/data-types/#string

2023-10-23 23:54 UTC, Ko1103 commented on openapi/components/schemas/TariffRestrictions.yaml
> +      Start time of day in local time, the time zone is defined in the time_zone field of the Location, for example 13:30, valid from this time of the day. Must be in 24h format with leading zeros. H
end_timeなども同様

2023-10-23 23:57 UTC, Ko1103 requested changes
Add `pattern` please

2023-10-24 04:56 UTC, ThaddeusJiang commented on openapi/components/schemas/TariffRestrictions.yaml
> +      Start time of day in local time, the time zone is defined in the time_zone field of the Location, for example 13:30, valid from this time of the day. Must be in 24h format with leading zeros. H
@Ko1103 対応した

2023-10-24 11:25 UTC, Ko1103 approved these changes
LGTM!

2023-10-25 02:11 UTC, merged